using System;
using System.IO;
using System.Net;
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Hosting;
using LiteDB;

namespace NL_SERVER
{
    public class Program
    {
        public static System.Collections.Concurrent.ConcurrentDictionary<string, string> IpToTokenMap = new();
        public static string DbPath => Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "neverlose.db");
        public static string BinsPath => Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "bins");

        public static void Main(string[] args)
        {
            if (args.Length > 0 && args[0] == "testdump") {
                using var testdb = new LiteDatabase(DbPath);
                var testuserObj = testdb.GetCollection<User>("users").FindOne(x => x.Username == "Tonyha7");
                if (testuserObj != null) {
                    var logs = testdb.GetCollection<LogEntry>("logs").Find(x => x.UserId == testuserObj.Id).OrderBy(x => x.EntryId).ToList();
                    var configLogs = logs.Where(x => x.EntryType == "Config").Select(x => new LogEntry { EntryId=x.EntryId, Timestamp=x.Timestamp, EntryType=x.EntryType, Author=x.Author, Name=x.Name }).ToList();
                    var scriptLogs = logs.Where(x => x.EntryType == "Script").Select(x => new LogEntry { EntryId=x.EntryId, Timestamp=x.Timestamp, EntryType=x.EntryType, Author=x.Author, Name=x.Name }).ToList();
                    var moduleBin = ModuleBuilder.BuildUserModule("Tonyha7", configLogs, scriptLogs);
                    Console.WriteLine("Generated bytes: " + (moduleBin?.Length ?? 0));
                }
                return;
            }
            if (!Directory.Exists(BinsPath))
                Directory.CreateDirectory(BinsPath);

            using (var db = new LiteDatabase(DbPath))
            {
                var users = db.GetCollection<User>("users");
                users.EnsureIndex(x => x.Username, true);
                users.EnsureIndex(x => x.AuthToken, true);
                var logs = db.GetCollection<LogEntry>("logs");
                logs.EnsureIndex(x => x.UserId);
            }

            var builder = WebApplication.CreateBuilder(args);
            builder.WebHost.ConfigureKestrel(options =>
            {
                var pfxPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "certs", "cert.pfx");
                var cert = TlsGenerator.EnsureSelfSignedCert(pfxPath);

                options.Listen(IPAddress.Any, 30030, listenOptions => 
                {
                    listenOptions.UseHttps(cert); // WebSocket port with TLS (WSS)
                }); 
                options.Listen(IPAddress.Any, 30031); // API / Admin port (HTTP)
            });
            
            var app = builder.Build();

            app.UseWebSockets(new WebSocketOptions { KeepAliveInterval = TimeSpan.FromMinutes(2) });

            // Middleware for WebSocket parsing
            app.Use(async (context, next) =>
            {
                if (context.Connection.LocalPort == 30030)
                {
                    if (context.WebSockets.IsWebSocketRequest)
                    {
                        var ws = await context.WebSockets.AcceptWebSocketAsync();
                        await HandleWebSocket(context, ws);
                    }
                    else
                    {
                        context.Response.StatusCode = 400;
                    }
                }
                else
                {
                    await next(context);
                }
            });

            MapAdminEndpoints(app);
            app.Run();
        }

        private static void MapAdminEndpoints(WebApplication app)
        {
            // Dummy implementations for API simulating the Express/Hyper APIs
            app.MapGet("/api/config", () => new { success = true });
            
            app.MapGet("/api/getavatar", async context => 
            {
                context.Response.Headers["Content-Type"] = "image/png";
                // Serve default avatar byte[]
                await context.Response.Body.WriteAsync(AvatarData.Bytes);
            });
            app.MapGet("/getavatar", async context => 
            {
                context.Response.Headers["Content-Type"] = "image/png";
                await context.Response.Body.WriteAsync(AvatarData.Bytes);
            });

            app.MapGet("/api/sendlog", () => new { success = true });
            app.MapGet("/sendlog", () => new { success = true });

            app.MapGet("/lua/{name}", (string name) => new { success = true });

            app.MapPost("/admin/seed", () => 
            {
                using var db = new LiteDatabase(DbPath);
                var baseModuleId = ObjectId.NewObjectId().ToString();
                var user = new User { Username = "seeded", AuthToken = "seed_token", BaseModuleId = baseModuleId, Serial = "NlBase64Serial==" };
                db.GetCollection<User>("users").Insert(user);
                return new { base_module_id = baseModuleId, user_id = user.Id.ToString(), username = user.Username, auth_token = user.AuthToken };
            });

            app.MapGet("/admin/users", () => 
            {
                using var db = new LiteDatabase(DbPath);
                return db.GetCollection<User>("users").FindAll();
            });

            app.MapPost("/admin/users", async context => 
            {
                using var db = new LiteDatabase(DbPath);
                var user = await System.Text.Json.JsonSerializer.DeserializeAsync<User>(context.Request.Body);
                db.GetCollection<User>("users").Insert(user);
                await context.Response.WriteAsJsonAsync(new { success = true, id = user.Id.ToString() });
            });

            app.MapGet("/admin/users/{userId}/logs", (string userId) =>
            {
                using var db = new LiteDatabase(DbPath);
                return db.GetCollection<LogEntry>("logs").Find(x => x.UserId == new ObjectId(userId));
            });

            app.MapPost("/admin/users/{userId}/logs", async (string userId, HttpContext context) =>
            {
                using var db = new LiteDatabase(DbPath);
                var log = await System.Text.Json.JsonSerializer.DeserializeAsync<LogEntry>(context.Request.Body);
                log.UserId = new ObjectId(userId);
                db.GetCollection<LogEntry>("logs").Insert(log);
                return new { success = true, id = log.Id.ToString() };
            });

            app.MapPut("/admin/users/{userId}/logs/{logId}", async (string userId, string logId, HttpContext context) =>
            {
                using var db = new LiteDatabase(DbPath);
                var log = await System.Text.Json.JsonSerializer.DeserializeAsync<LogEntry>(context.Request.Body);
                log.Id = new ObjectId(logId);
                log.UserId = new ObjectId(userId);
                db.GetCollection<LogEntry>("logs").Update(log);
                return new { success = true };
            });

            app.MapDelete("/admin/users/{userId}/logs/{logId}", (string userId, string logId) =>
            {
                using var db = new LiteDatabase(DbPath);
                db.GetCollection<LogEntry>("logs").Delete(new ObjectId(logId));
                return new { success = true };
            });
        }

        private static async Task HandleWebSocket(HttpContext context, WebSocket ws)
        {
            var ip = context.Connection.RemoteIpAddress?.ToString() ?? "unknown";
            Console.WriteLine($"[WS] Connection established from {ip}, waiting for first message...");

            var buffer = new byte[1024 * 4];
            var receiveResult = await ws.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
            if (receiveResult.MessageType == WebSocketMessageType.Close)
            {
                await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "", CancellationToken.None);
                return;
            }

            var textStr = Encoding.UTF8.GetString(buffer, 0, receiveResult.Count);
            var token = textStr.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries).FirstOrDefault()?.Trim() ?? "";

            if (string.IsNullOrEmpty(token))
            {
                Console.WriteLine("[WS] No token found in first message, closing");
                await ws.CloseAsync(WebSocketCloseStatus.ProtocolError, "No token", CancellationToken.None);
                return;
            }

            Console.WriteLine($"[WS] Token from first message: {token}");
            IpToTokenMap[ip] = token;
            Console.WriteLine($"[WS] Stored IP->token mapping: {ip} -> {token}");

            // Simulate the 3 frames as described:
            // 1. Auth JSON
            var authJson = System.Text.Json.JsonSerializer.Serialize(new { Type = "Auth", Message = "fz8XfUGGBvylN7IW", Data = "5aAxpFpna5QqvYMv" });
            await ws.SendAsync(Encoding.UTF8.GetBytes(authJson), WebSocketMessageType.Text, true, CancellationToken.None);

            // 2. Module BIN (Built dynamically from DB)
            byte[] moduleBin = new byte[0];
            using (var db = new LiteDatabase(DbPath))
            {
                var users = db.GetCollection<User>("users");
                var user = users.FindOne(x => x.AuthToken == token);
                if (user == null)
                {
                    Console.WriteLine($"[WS] User not found for token {token}, auto-creating dummy user.");
                    user = new User 
                    { 
                        Username = "Tonyha7", 
                        AuthToken = token, 
                        Serial = "NlBase64Serial==", 
                        BaseModuleId = ObjectId.NewObjectId().ToString() 
                    };
                    users.Insert(user);
                    
                    var logsColl = db.GetCollection<LogEntry>("logs");
                    logsColl.Insert(new LogEntry { UserId = user.Id, EntryId = 28, Timestamp = 1771520809, EntryType = "Script", Author = "Tonyha7", Name = "Script" });
                    logsColl.Insert(new LogEntry { UserId = user.Id, EntryId = 29, Timestamp = 1771520095, EntryType = "Script", Author = "Tonyha7", Name = "Script" });
                    logsColl.Insert(new LogEntry { UserId = user.Id, EntryId = 30, Timestamp = 1771520084, EntryType = "Script", Author = "Tonyha7", Name = "Script" });
                    logsColl.Insert(new LogEntry { UserId = user.Id, EntryId = 31, Timestamp = 1771506314, EntryType = "Script", Author = "Tonyha7", Name = "Script" });
                    logsColl.Insert(new LogEntry { UserId = user.Id, EntryId = 32, Timestamp = 1771506310, EntryType = "Script", Author = "Tonyha7", Name = "Script" });
                    logsColl.Insert(new LogEntry { UserId = user.Id, EntryId = 33, Timestamp = 1771506310, EntryType = "Script", Author = "Tonyha7", Name = "Script" });

                    logsColl.Insert(new LogEntry { UserId = user.Id, EntryId = 40769, Timestamp = 0, EntryType = "Config", Author = "Tonyha7", Name = "Config" });
                }

                var logs = db.GetCollection<LogEntry>("logs").Find(x => x.UserId == user.Id).OrderBy(x => x.EntryId).ToList();
                var configLogs = logs.Where(x => x.EntryType == "Config").Select(x => new LogEntry { EntryId=x.EntryId, Timestamp=x.Timestamp, EntryType=x.EntryType, Author=x.Author, Name=x.Name }).ToList();
                var scriptLogs = logs.Where(x => x.EntryType == "Script").Select(x => new LogEntry { EntryId=x.EntryId, Timestamp=x.Timestamp, EntryType=x.EntryType, Author=x.Author, Name=x.Name }).ToList();
                
                moduleBin = ModuleBuilder.BuildUserModule(user.Username, configLogs, scriptLogs);
            }
            if (moduleBin != null && moduleBin.Length > 0)
                await ws.SendAsync(moduleBin, WebSocketMessageType.Binary, true, CancellationToken.None);

            // 3. Key BIN
            byte[] keyBin = new byte[] { 
                0xF2, 0xBC, 0x8A, 0x7F, 0xE9, 0x9E, 0x1F, 0x01, 0x37, 0xB2, 0xDD, 0x77, 0xEC, 0x02, 0x5C, 0x6E, 
                0xB1, 0xF8, 0x6B, 0x68, 0xBC, 0x82, 0x8D, 0x50, 0x33, 0x4E, 0xF2, 0x2F, 0x4C, 0x3D, 0xD7, 0x55, 
                0xFF, 0x39, 0xAF, 0x83, 0x76, 0x4B, 0x9F, 0xA6, 0x1E, 0xEF, 0x1C, 0x35, 0x1D, 0xE1, 0x45, 0x93, 
                0x84, 0xB7, 0xD2, 0x58, 0x90, 0xE8, 0x94, 0xA9, 0x67, 0xF5, 0xF4, 0x84, 0x4E, 0xF9, 0xC2, 0x54, 
                0xD6, 0xAE, 0x85, 0x58, 0xF0, 0x49, 0x09, 0xBB, 0x76, 0xFE, 0x06, 0x49, 0xFF, 0xFA, 0x38, 0xF3 
            };
            await ws.SendAsync(keyBin, WebSocketMessageType.Binary, true, CancellationToken.None);

            while (ws.State == WebSocketState.Open)
            {
                var result = await ws.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
                if (result.MessageType == WebSocketMessageType.Close)
                    break;
                
                if (result.MessageType == WebSocketMessageType.Binary)
                {
                    var data = new byte[result.Count];
                    Array.Copy(buffer, data, result.Count);
                    
                    try 
                    {
                        var decrypted = ModuleBuilder.DecryptAES128CBC(data);
                        var decompressed = ModuleBuilder.DecompressLZ4WithHeader(decrypted);
                        Console.WriteLine($"[WS] Decrypted and decompressed incoming message! Length: {decompressed.Length}");
                        
                        var clientMsg = ClientMsgParser.Parse(decompressed);
                        byte[] reply = null;

                        using (var db = new LiteDatabase(DbPath))
                        {
                            var users = db.GetCollection<User>("users");
                            var userObj = users.FindOne(x => x.AuthToken == token);
                            if (userObj != null)
                            {
                                var logs = db.GetCollection<LogEntry>("logs");
                                
                                if (clientMsg.MsgType == 3 && clientMsg.Payload is CreateEntryMsg createEntry) // CreateEntry
                                {
                                    int nextId = logs.Count() > 0 ? logs.Max(x => x.EntryId) + 1 : 1;
                                    var ts = (long)(DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds;
                                    var logType = createEntry.EntryType == 1 ? "Script" : "Config";

                                    var log = new LogEntry
                                    {
                                        UserId = userObj.Id,
                                        EntryId = nextId,
                                        Timestamp = ts,
                                        EntryType = logType,
                                        Author = userObj.Username,
                                        Name = createEntry.Name
                                    };
                                    logs.Insert(log);

                                    // Construct response FlatBuffer
                                    var nb = new Google.FlatBuffers.FlatBufferBuilder(128);
                                    var nAuthor = nb.CreateString(userObj.Username);
                                    var nType = nb.CreateString(logType);
                                    nl.LogEntry.StartLogEntry(nb);
                                    nl.LogEntry.AddEntryId(nb, (uint)nextId);
                                    nl.LogEntry.AddTimestamp(nb, (uint)ts);
                                    nl.LogEntry.AddEntryType(nb, nType);
                                    nl.LogEntry.AddAuthor(nb, nAuthor);
                                    var logOffset = nl.LogEntry.EndLogEntry(nb);
                                    nb.Finish(logOffset.Value);

                                    var ob = new Google.FlatBuffers.FlatBufferBuilder(128);
                                    var payloadOffset = nl.ModuleWrapper.CreatePayloadVector(ob, nb.SizedByteArray());
                                    nl.ModuleWrapper.StartModuleWrapper(ob);
                                    nl.ModuleWrapper.AddVersion(ob, 3); // type = 3
                                    nl.ModuleWrapper.AddPayload(ob, payloadOffset);
                                    var wrapOffset = nl.ModuleWrapper.EndModuleWrapper(ob);
                                    ob.Finish(wrapOffset.Value);

                                    byte[] replyPlain = ob.SizedByteArray();
                                    reply = ModuleBuilder.EncryptAES128CBC(ModuleBuilder.CompressLZ4WithHeader(replyPlain));
                                }
                                else if (clientMsg.MsgType == 1 && clientMsg.Payload is UpdateEntryMsg updateEntry) // UpdateEntry
                                {
                                    var target = logs.FindOne(x => x.UserId == userObj.Id && x.EntryId == updateEntry.EntryId);
                                    if (target != null)
                                    {
                                        if (updateEntry.Timestamp.HasValue) target.Timestamp = updateEntry.Timestamp.Value;
                                        if (updateEntry.Name != null) target.Name = updateEntry.Name;
                                        if (updateEntry.Content != null) target.Content = updateEntry.Content;
                                        logs.Update(target);
                                    }
                                    else
                                    {
                                        // Create script explicitly?
                                    }
                                }
                            }
                        }

                        if (reply != null)
                        {
                            Console.WriteLine($"[WS] Sending reply to Client ({reply.Length} bytes)");
                            await ws.SendAsync(reply, WebSocketMessageType.Binary, true, CancellationToken.None);
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"[WS] Failed to decrypt/parse incoming binary: {ex.Message}");
                    }
                }
            }
            await ws.CloseAsync(WebSocketCloseStatus.NormalClosure, "", CancellationToken.None);
        }
    }

    public class User
    {
        public ObjectId Id { get; set; }
        public string Username { get; set; }
        public string AuthToken { get; set; }
        public string Serial { get; set; }
        public string BaseModuleId { get; set; }
    }

    public class LogEntry
    {
        public ObjectId Id { get; set; }
        public int EntryId { get; set; }
        public long Timestamp { get; set; }
        public string EntryType { get; set; }
        public string Author { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public ObjectId UserId { get; set; }
    }
}
