// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace nl
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// Language definition with optional translation data
public struct Language : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Language GetRootAsLanguage(ByteBuffer _bb) { return GetRootAsLanguage(_bb, new Language()); }
  public static Language GetRootAsLanguage(ByteBuffer _bb, Language obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Language __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Unknown0 { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnknown0Bytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUnknown0Bytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUnknown0Array() { return __p.__vector_as_array<byte>(4); }
  public string Unknown1 { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnknown1Bytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetUnknown1Bytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUnknown1Array() { return __p.__vector_as_array<byte>(6); }
  public string Code { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCodeBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetCodeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetCodeArray() { return __p.__vector_as_array<byte>(8); }
  public string Unknown3 { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnknown3Bytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetUnknown3Bytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetUnknown3Array() { return __p.__vector_as_array<byte>(10); }
  public string EnglishName { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEnglishNameBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetEnglishNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetEnglishNameArray() { return __p.__vector_as_array<byte>(12); }
  public string NativeName { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNativeNameBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetNativeNameBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetNativeNameArray() { return __p.__vector_as_array<byte>(14); }
  public byte Translations(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int TranslationsLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTranslationsBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetTranslationsBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetTranslationsArray() { return __p.__vector_as_array<byte>(16); }

  public static Offset<nl.Language> CreateLanguage(FlatBufferBuilder builder,
      StringOffset unknown_0Offset = default(StringOffset),
      StringOffset unknown_1Offset = default(StringOffset),
      StringOffset codeOffset = default(StringOffset),
      StringOffset unknown_3Offset = default(StringOffset),
      StringOffset english_nameOffset = default(StringOffset),
      StringOffset native_nameOffset = default(StringOffset),
      VectorOffset translationsOffset = default(VectorOffset)) {
    builder.StartTable(7);
    Language.AddTranslations(builder, translationsOffset);
    Language.AddNativeName(builder, native_nameOffset);
    Language.AddEnglishName(builder, english_nameOffset);
    Language.AddUnknown3(builder, unknown_3Offset);
    Language.AddCode(builder, codeOffset);
    Language.AddUnknown1(builder, unknown_1Offset);
    Language.AddUnknown0(builder, unknown_0Offset);
    return Language.EndLanguage(builder);
  }

  public static void StartLanguage(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddUnknown0(FlatBufferBuilder builder, StringOffset unknown0Offset) { builder.AddOffset(0, unknown0Offset.Value, 0); }
  public static void AddUnknown1(FlatBufferBuilder builder, StringOffset unknown1Offset) { builder.AddOffset(1, unknown1Offset.Value, 0); }
  public static void AddCode(FlatBufferBuilder builder, StringOffset codeOffset) { builder.AddOffset(2, codeOffset.Value, 0); }
  public static void AddUnknown3(FlatBufferBuilder builder, StringOffset unknown3Offset) { builder.AddOffset(3, unknown3Offset.Value, 0); }
  public static void AddEnglishName(FlatBufferBuilder builder, StringOffset englishNameOffset) { builder.AddOffset(4, englishNameOffset.Value, 0); }
  public static void AddNativeName(FlatBufferBuilder builder, StringOffset nativeNameOffset) { builder.AddOffset(5, nativeNameOffset.Value, 0); }
  public static void AddTranslations(FlatBufferBuilder builder, VectorOffset translationsOffset) { builder.AddOffset(6, translationsOffset.Value, 0); }
  public static VectorOffset CreateTranslationsVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateTranslationsVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTranslationsVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTranslationsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTranslationsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<nl.Language> EndLanguage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<nl.Language>(o);
  }
}


static public class LanguageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Unknown0*/, false)
      && verifier.VerifyString(tablePos, 6 /*Unknown1*/, false)
      && verifier.VerifyString(tablePos, 8 /*Code*/, false)
      && verifier.VerifyString(tablePos, 10 /*Unknown3*/, false)
      && verifier.VerifyString(tablePos, 12 /*EnglishName*/, false)
      && verifier.VerifyString(tablePos, 14 /*NativeName*/, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*Translations*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
