// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace nl
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// Log entry for script/config change history
public struct LogEntry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static LogEntry GetRootAsLogEntry(ByteBuffer _bb) { return GetRootAsLogEntry(_bb, new LogEntry()); }
  public static LogEntry GetRootAsLogEntry(ByteBuffer _bb, LogEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LogEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint EntryId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint Timestamp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Unknown2 { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUnknown2Bytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetUnknown2Bytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetUnknown2Array() { return __p.__vector_as_array<byte>(8); }
  public string EntryType { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEntryTypeBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetEntryTypeBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetEntryTypeArray() { return __p.__vector_as_array<byte>(10); }
  public string Author { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAuthorBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetAuthorBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetAuthorArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<nl.LogEntry> CreateLogEntry(FlatBufferBuilder builder,
      uint entry_id = 0,
      uint timestamp = 0,
      StringOffset unknown_2Offset = default(StringOffset),
      StringOffset entry_typeOffset = default(StringOffset),
      StringOffset authorOffset = default(StringOffset)) {
    builder.StartTable(5);
    LogEntry.AddAuthor(builder, authorOffset);
    LogEntry.AddEntryType(builder, entry_typeOffset);
    LogEntry.AddUnknown2(builder, unknown_2Offset);
    LogEntry.AddTimestamp(builder, timestamp);
    LogEntry.AddEntryId(builder, entry_id);
    return LogEntry.EndLogEntry(builder);
  }

  public static void StartLogEntry(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddEntryId(FlatBufferBuilder builder, uint entryId) { builder.AddUint(0, entryId, 0); }
  public static void AddTimestamp(FlatBufferBuilder builder, uint timestamp) { builder.AddUint(1, timestamp, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, StringOffset unknown2Offset) { builder.AddOffset(2, unknown2Offset.Value, 0); }
  public static void AddEntryType(FlatBufferBuilder builder, StringOffset entryTypeOffset) { builder.AddOffset(3, entryTypeOffset.Value, 0); }
  public static void AddAuthor(FlatBufferBuilder builder, StringOffset authorOffset) { builder.AddOffset(4, authorOffset.Value, 0); }
  public static Offset<nl.LogEntry> EndLogEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<nl.LogEntry>(o);
  }
}


static public class LogEntryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EntryId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Timestamp*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 8 /*Unknown2*/, false)
      && verifier.VerifyString(tablePos, 10 /*EntryType*/, false)
      && verifier.VerifyString(tablePos, 12 /*Author*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
