// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace nl
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// Inner module data (nested inside outer wrapper as [ubyte])
public struct ModuleData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ModuleData GetRootAsModuleData(ByteBuffer _bb) { return GetRootAsModuleData(_bb, new ModuleData()); }
  public static ModuleData GetRootAsModuleData(ByteBuffer _bb, ModuleData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ModuleData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Unknown0 { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte ExtraData(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int ExtraDataLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetExtraDataBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetExtraDataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetExtraDataArray() { return __p.__vector_as_array<byte>(6); }
  public string Author { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAuthorBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetAuthorBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetAuthorArray() { return __p.__vector_as_array<byte>(8); }
  public uint Checksum { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public nl.LogEntry? ConfigLog(int j) { int o = __p.__offset(12); return o != 0 ? (nl.LogEntry?)(new nl.LogEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ConfigLogLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public nl.LogEntry? ScriptLog(int j) { int o = __p.__offset(14); return o != 0 ? (nl.LogEntry?)(new nl.LogEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ScriptLogLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public uint BufferCapacity { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public nl.Language? Languages(int j) { int o = __p.__offset(18); return o != 0 ? (nl.Language?)(new nl.Language()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LanguagesLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
  public uint Enabled { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte SkinData(int j) { int o = __p.__offset(22); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int SkinDataLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSkinDataBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetSkinDataBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetSkinDataArray() { return __p.__vector_as_array<byte>(22); }
  public uint Unknown10 { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string AuthToken { get { int o = __p.__offset(26); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAuthTokenBytes() { return __p.__vector_as_span<byte>(26, 1); }
#else
  public ArraySegment<byte>? GetAuthTokenBytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public byte[] GetAuthTokenArray() { return __p.__vector_as_array<byte>(26); }

  public static Offset<nl.ModuleData> CreateModuleData(FlatBufferBuilder builder,
      uint unknown_0 = 0,
      VectorOffset extra_dataOffset = default(VectorOffset),
      StringOffset authorOffset = default(StringOffset),
      uint checksum = 0,
      VectorOffset config_logOffset = default(VectorOffset),
      VectorOffset script_logOffset = default(VectorOffset),
      uint buffer_capacity = 0,
      VectorOffset languagesOffset = default(VectorOffset),
      uint enabled = 0,
      VectorOffset skin_dataOffset = default(VectorOffset),
      uint unknown_10 = 0,
      StringOffset auth_tokenOffset = default(StringOffset)) {
    builder.StartTable(12);
    ModuleData.AddAuthToken(builder, auth_tokenOffset);
    ModuleData.AddUnknown10(builder, unknown_10);
    ModuleData.AddSkinData(builder, skin_dataOffset);
    ModuleData.AddEnabled(builder, enabled);
    ModuleData.AddLanguages(builder, languagesOffset);
    ModuleData.AddBufferCapacity(builder, buffer_capacity);
    ModuleData.AddScriptLog(builder, script_logOffset);
    ModuleData.AddConfigLog(builder, config_logOffset);
    ModuleData.AddChecksum(builder, checksum);
    ModuleData.AddAuthor(builder, authorOffset);
    ModuleData.AddExtraData(builder, extra_dataOffset);
    ModuleData.AddUnknown0(builder, unknown_0);
    return ModuleData.EndModuleData(builder);
  }

  public static void StartModuleData(FlatBufferBuilder builder) { builder.StartTable(12); }
  public static void AddUnknown0(FlatBufferBuilder builder, uint unknown0) { builder.AddUint(0, unknown0, 0); }
  public static void AddExtraData(FlatBufferBuilder builder, VectorOffset extraDataOffset) { builder.AddOffset(1, extraDataOffset.Value, 0); }
  public static VectorOffset CreateExtraDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateExtraDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateExtraDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateExtraDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartExtraDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddAuthor(FlatBufferBuilder builder, StringOffset authorOffset) { builder.AddOffset(2, authorOffset.Value, 0); }
  public static void AddChecksum(FlatBufferBuilder builder, uint checksum) { builder.AddUint(3, checksum, 0); }
  public static void AddConfigLog(FlatBufferBuilder builder, VectorOffset configLogOffset) { builder.AddOffset(4, configLogOffset.Value, 0); }
  public static VectorOffset CreateConfigLogVector(FlatBufferBuilder builder, Offset<nl.LogEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateConfigLogVectorBlock(FlatBufferBuilder builder, Offset<nl.LogEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateConfigLogVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<nl.LogEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateConfigLogVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<nl.LogEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartConfigLogVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddScriptLog(FlatBufferBuilder builder, VectorOffset scriptLogOffset) { builder.AddOffset(5, scriptLogOffset.Value, 0); }
  public static VectorOffset CreateScriptLogVector(FlatBufferBuilder builder, Offset<nl.LogEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateScriptLogVectorBlock(FlatBufferBuilder builder, Offset<nl.LogEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateScriptLogVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<nl.LogEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateScriptLogVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<nl.LogEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartScriptLogVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBufferCapacity(FlatBufferBuilder builder, uint bufferCapacity) { builder.AddUint(6, bufferCapacity, 0); }
  public static void AddLanguages(FlatBufferBuilder builder, VectorOffset languagesOffset) { builder.AddOffset(7, languagesOffset.Value, 0); }
  public static VectorOffset CreateLanguagesVector(FlatBufferBuilder builder, Offset<nl.Language>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLanguagesVectorBlock(FlatBufferBuilder builder, Offset<nl.Language>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLanguagesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<nl.Language>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLanguagesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<nl.Language>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartLanguagesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEnabled(FlatBufferBuilder builder, uint enabled) { builder.AddUint(8, enabled, 0); }
  public static void AddSkinData(FlatBufferBuilder builder, VectorOffset skinDataOffset) { builder.AddOffset(9, skinDataOffset.Value, 0); }
  public static VectorOffset CreateSkinDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateSkinDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSkinDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSkinDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSkinDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddUnknown10(FlatBufferBuilder builder, uint unknown10) { builder.AddUint(10, unknown10, 0); }
  public static void AddAuthToken(FlatBufferBuilder builder, StringOffset authTokenOffset) { builder.AddOffset(11, authTokenOffset.Value, 0); }
  public static Offset<nl.ModuleData> EndModuleData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<nl.ModuleData>(o);
  }
}


static public class ModuleDataVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Unknown0*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*ExtraData*/, 1 /*byte*/, false)
      && verifier.VerifyString(tablePos, 8 /*Author*/, false)
      && verifier.VerifyField(tablePos, 10 /*Checksum*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 12 /*ConfigLog*/, nl.LogEntryVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 14 /*ScriptLog*/, nl.LogEntryVerify.Verify, false)
      && verifier.VerifyField(tablePos, 16 /*BufferCapacity*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 18 /*Languages*/, nl.LanguageVerify.Verify, false)
      && verifier.VerifyField(tablePos, 20 /*Enabled*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 22 /*SkinData*/, 1 /*byte*/, false)
      && verifier.VerifyField(tablePos, 24 /*Unknown10*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 26 /*AuthToken*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
