// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace nl
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

/// Outer wrapper — the root type of the decompressed file
public struct ModuleWrapper : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ModuleWrapper GetRootAsModuleWrapper(ByteBuffer _bb) { return GetRootAsModuleWrapper(_bb, new ModuleWrapper()); }
  public static ModuleWrapper GetRootAsModuleWrapper(ByteBuffer _bb, ModuleWrapper obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyModuleWrapper(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ModuleWrapperVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ModuleWrapper __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Payload(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int PayloadLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPayloadBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPayloadBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPayloadArray() { return __p.__vector_as_array<byte>(6); }
  public nl.ModuleData? GetPayloadAsModuleData() { int o = __p.__offset(6); return o != 0 ? (nl.ModuleData?)(new nl.ModuleData()).__assign(__p.__indirect(__p.__vector(o)), __p.bb) : null; }

  public static Offset<nl.ModuleWrapper> CreateModuleWrapper(FlatBufferBuilder builder,
      uint version = 0,
      VectorOffset payloadOffset = default(VectorOffset)) {
    builder.StartTable(2);
    ModuleWrapper.AddPayload(builder, payloadOffset);
    ModuleWrapper.AddVersion(builder, version);
    return ModuleWrapper.EndModuleWrapper(builder);
  }

  public static void StartModuleWrapper(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddVersion(FlatBufferBuilder builder, uint version) { builder.AddUint(0, version, 0); }
  public static void AddPayload(FlatBufferBuilder builder, VectorOffset payloadOffset) { builder.AddOffset(1, payloadOffset.Value, 0); }
  public static VectorOffset CreatePayloadVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePayloadVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePayloadVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePayloadVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPayloadVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<nl.ModuleWrapper> EndModuleWrapper(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<nl.ModuleWrapper>(o);
  }
  public static void FinishModuleWrapperBuffer(FlatBufferBuilder builder, Offset<nl.ModuleWrapper> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedModuleWrapperBuffer(FlatBufferBuilder builder, Offset<nl.ModuleWrapper> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class ModuleWrapperVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Version*/, 4 /*uint*/, 4, false)
      && verifier.VerifyNestedBuffer(tablePos, 6 /*Payload*/, nl.ModuleDataVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
